# Cloud Build configuration for Backend
# Automatically builds and deploys to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/researchbuddy-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/researchbuddy-backend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/researchbuddy-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/researchbuddy-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'researchbuddy-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/researchbuddy-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'

images:
  - 'gcr.io/$PROJECT_ID/researchbuddy-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/researchbuddy-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
